trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - SchoolPortal.Database.Deploy/*
    - SchoolPortal.Database.Deploy.OLD/*
    - azure-api-pipeline.yaml
    - azure-db-pipeline.yaml
    - README.md

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: azure-sql-variables
  - name: BuildConfiguration
    value: 'Release'

stages:
  - stage: Build
    jobs:
      - job: BuildAndTest
        steps:

        - task: UseDotNet@2
          displayName: Use dot net 9
          inputs:
            version: '9.x'

        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(BuildConfiguration)'

        - script: |
            echo "Starting SQL Server container..."
            docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 --name sqlcontainer -d mcr.microsoft.com/mssql/server:2019-latest
          displayName: 'Start SQL Server container'

        - script: |
            echo "Waiting for SQL Server to start..."
            sleep 15
          displayName: 'Wait for SQL Server to start'

        - script: |
            echo "Setting database connection string..."
            echo "##vso[task.setvariable variable=DatabaseConnectionString]Server=localhost;Database=SchoolPortalTest;User=sa;Password=yourStrong(!)Password;Integrated Security=false;Encrypt=false;TrustServerCertificate=true;Connection Timeout=30;"
          displayName: 'Set database connection string'

        - task: DotNetCoreCLI@2
          displayName: 'Run Unit Tests'
          inputs:
            command: 'test'
            projects: '**/SchoolPortal.UnitTests/*.csproj'
            arguments: '--configuration $(BuildConfiguration) --no-build --collect "Code coverage"'
            testRunTitle: 'School Portal Api Unit tests'

        - task: DotNetCoreCLI@2
          displayName: 'Run Integration Tests'
          inputs:
            command: 'test'
            projects: '**/SchoolPortal.IntegrationTests/*.csproj'
            arguments: '--configuration $(BuildConfiguration) --no-build --collect "Code coverage"'
            testRunTitle: 'School Portal API Integration Tests'
          env:
            DatabaseConnection: $(DatabaseConnectionString)

        - script: |
            echo "Stopping and removing SQL Server container..."
            docker stop sqlcontainer
            docker rm sqlcontainer
          displayName: 'Stop and remove SQL Server container'

        - task: DotNetCoreCLI@2
          displayName: 'Publish SchoolPortal.Api'
          inputs:
            command: publish
            publishWebProjects: false
            projects: SchoolPortal.Api/SchoolPortal.Api.csproj
            arguments: '--configuration $(BuildConfiguration) --output "$(build.artifactstagingdirectory)/Api"'
            modifyOutputPath: false
            zipAfterPublish: false

        - task: ArchiveFiles@2
          displayName: Archive files
          inputs:
            rootFolderOrFile: $(Build.ArtifactStagingDirectory)/Api
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/build.zip
            replaceExistingArchive: true

        - task: PublishPipelineArtifact@1
          displayName: Publish build artifact
          inputs:
            targetPath: $(Build.ArtifactStagingDirectory)/build.zip
            publishLocation: 'pipeline'
            artifact: buildArtifact

  - stage: DeployToDev
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))

    variables:
      ConnectionStrings.DatabaseConnection: 'Server=tcp:$(sqlurl),1433;Initial Catalog=SchoolPortalDev;Persist Security Info=False;User ID=$(sqldevuser);Password=$(sqldevpass);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'

    jobs:
    - job: DeployToDevAzureAppService
      steps:

        - task: DownloadPipelineArtifact@2
          displayName: Download build artifact
          inputs:
            artifact: buildArtifact
            path: $(Pipeline.Workspace)/build

        # Update appsettings.json via FileTransform task.
        - task: FileTransform@1
          displayName: 'File transformation: appsettings.json'
          inputs:
            folderPath: '$(Pipeline.Workspace)/build/build.zip'
            targetFiles: '**/appsettings.json'
            fileType: json

        - task: AzureRmWebAppDeployment@4
          displayName: Deploy to Dev Azure App Service
          inputs:
            connectionType: AzureRM
            azureSubscription: SchoolPortalAPI
            resourceGroupName: SchoolPortalApi
            appType: webAppLinux
            webAppName: eduapi
            packageForLinux: $(Pipeline.Workspace)/build/build.zip
            deployToSlotOrASE: true
            slotName: dev
            AppSettings: '-ASPNETCORE_ENVIRONMENT Development'

  - stage: DeployToProd
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

    variables:
      Serilog.MinimumLevel.Override.Microsoft: Debug
      ConnectionStrings.DatabaseConnection: 'Server=tcp:$(sqlurl),1433;Initial Catalog=SchoolPortal;Persist Security Info=False;User ID=$(sqlproduser);Password=$(sqlprodpass);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'

    jobs:
    - job: DeployToProdAzureAppService
      steps:

        - task: DownloadPipelineArtifact@2
          displayName: Download build artifact
          inputs:
            artifact: buildArtifact
            path: $(Pipeline.Workspace)/build

        # Update appsettings.json via FileTransform task.
        - task: FileTransform@1
          displayName: 'File transformation: appsettings.json'
          inputs:
            folderPath: '$(Pipeline.Workspace)/build/build.zip'
            targetFiles: '**/appsettings.json'
            fileType: json

        - task: AzureRmWebAppDeployment@4
          displayName: Deploy to Prod Azure App Service
          inputs:
            connectionType: AzureRM
            azureSubscription: SchoolPortalAPI
            resourceGroupName: SchoolPortalApi
            appType: webAppLinux
            webAppName: eduapi
            packageForLinux: $(Pipeline.Workspace)/build/build.zip
            AppSettings: '-ASPNETCORE_ENVIRONMENT Production'
